version: '3'
services:
  mysql:
    build: ./server/mysql
    ports:
      - 5307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    container_name: mysql
  redis:
    build:
      context: ./server/redis
    ports:
      - 6370:6379
    volumes:
      - ./data/redis/data:/usr/local/redis/data
      - ./log/redis:/usr/local/redis
    container_name: redis
    networks:
      - backend
    restart: always
  php:
    build:
      context: ./server/php
    ports:
      - 9001:9000
      - 8971:8971
      - 8972:8972
      - 8973:8973
      - 8000:8000
    volumes:
      - ./www:/var/www/html
      - ./log/php:/data/log
    # command: bash -c "/systemstart.sh && /usr/local/sbin/php-fpm"
    networks:
      - backend
    container_name: php
  nginx:
    build:
      context: ./server/nginx
    ports:
      - 80:80
      - 81:81
      - 82:82
      - 83:83
      - 84:84
      - 85:85
      - 86:86
      - 90:90
      - 91:91
      - 92:92


    volumes:
      - ./www:/usr/share/nginx/html
      - ./server/nginx/conf.d:/etc/nginx/conf.d
      - ./server/nginx/cert:/etc/nginx/cert
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx

    networks:
      - backend
    restart: always
    links:
      - php
    container_name: nginx
networks:
  backend:





